GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "zj",
    "password": "p@ssword"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "zj",
    "password": "p@ssword"
}

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiemoiLCJpYXQiOjE2MzI1NjYyNzR9.3vEP-v3kWOG4aQ7Q5JUXlmNAEJZAcIL6FYVy3wTXJkA